hello-windows:
  before_script:
    - set PATH="E:\Program Files (x86)\CMake\bin";%PATH%
  script:
    - mkdir build && cd build
    - cmake ..
    - cmake --build .
  tags:
    - windows

hello-linux:
  script:
    - mkdir build && cd build
    - cmake ..
    - cmake --build .
  tags:
    - linux
