language: cpp

sudo: required
dist: trusty

os:
  - linux

compiler:
  - gcc

addons:
  apt:
    packages:
      - cmake
      - libsfml-dev
      - cpputest
      - gcc-5
      - g++-5

env:
  - C_COMPILER=gcc-5
  - CXX_COMPILER=g++-5

script:
    - mkdir build && cd build
    - cmake -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_CXX_COMPILER=$CXX_COMPILER ..
    - cmake --build .
