language: cpp

sudo: required
dist: trusty

os:
  - linux

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq && sudo apt-get install -qq libsfml-dev cmake

script:
    - mkdir build && cd build
    - cmake ..
    - cmake --build .
