version: 1.0.{build}

platform:
  - x86
  - x64

environment:
  MINGW_VERSION: 5.3.0
  SFML_VERSION: 2.3.2
  CPPUTEST_VERSION: 3.8
  GENERATOR: MSYS Makefiles
  SFML_COMPILER: windows-gcc-4.9.2-mingw

install:
  - cmd: scripts/install.bat

build_script:
  - cmd: scripts/build.bat
