version: 1.0.{build}

platform:
  - x86
  - x64

environment:
  MINGW_VERSION: 4.9.3
  SFML_VERSION: 2.3.2
  CPPUTEST_VERSION: 3.8
  GENERATOR: MinGW Makefiles
  SFML_COMPILER: windows-gcc-4.9.2-mingw

install:
  - cmd: scripts\install.bat

build_script:
  - cmd: scripts\build.bat

test_script:
  - ctest -V .

cache:
  - dependencies -> appveyor.yml, scripts\install.bat
  - C:\tools\mingw32 -> appveyor.yml, scripts\install.bat
  - C:\tools\mingw64 -> appveyor.yml, scripts\install.bat
