version: 1.0.{build}

platform:
  - x86
  - x64

environment:
  SFML_VERSION: 2.3.2
  BOOST_VERSION: 1.60.0
  CPPUTEST_VERSION: 3.8
  GENERATOR: MinGW Makefiles
  SFML_COMPILER: windows-gcc-4.9.2-mingw

install:
  - cmd: scripts\install.bat

build_script:
  - cmd: scripts\build.bat

test_script:
  - ctest -V .

cache:
  - dependencies -> appveyor.yml, scripts\install.bat
  - C:\toolchain\mingw -> appveyor.yml, scripts\install.bat
