version: 0.1.0.{build}-{branch}

platform:
  - x86
  - x64

environment:
  toolchain_path: C:\toolchain
  toolchain: mingw
  CMAKE_GENERATOR: MinGW Makefiles
  BUILD_DIR: build

install:
  - cmd: scripts\install-common.bat
  - cmd: scripts\install-toolchain.bat
  - cmd: scripts\install-dependencies.bat

build_script:
  - cmd: scripts\build.bat

test_script:
  - cmd: scripts\test.bat

artifacts:
  - path: $(BUILD_DIR)\tetris*.zip
    name: tetris

deploy:
  - provider: GitHub
    auth_token:
      secure: a7q6wJf8WGTKjytaB3jEpqzAQUhCoYIYiQqBRPEX5IGFjAOkc9X+B9c1GzwuOpEV
    artifact: tetris
    prerelease: true
    force_update: true
    on:
      branch: master
      appveyor_repo_tag: true

cache:
  - '%toolchain_path%\%toolchain% -> scripts\install-toolchain.bat, scripts\install-common.bat'
  - dependencies -> scripts\install-dependencies.bat, scripts\install-common.bat
