version: 1.0.{build}

platform:
  - x86
  - x64

environment:
  CMAKE_GENERATOR: MinGW Makefiles
  BUILD_DIR: build

install:
  - cmd: scripts\install-common.bat
  - cmd: scripts\install-toolchain.bat
  - cmd: scripts\install-dependencies.bat

build_script:
  - cmd: scripts\build.bat

test_script:
  - cmd: scripts\test.bat

artifacts:
  - path: tetris*.zip

cache:
  - '%toolchain_path%\%toolchain% -> scripts\install-toolchain.bat, scripts\install-common.bat'
  - dependencies -> scripts\install-dependencies.bat, scripts\install-common.bat
