# This file was generated by CMake because it detected TRY_RUN() commands
# in crosscompiling mode. It will be overwritten by the next CMake run.
# Copy it to a safe location, set the variables to appropriate values
# and use it then to preset the CMake cache (using -C).


# THREADS_PTHREAD_ARG
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set THREADS_PTHREAD_ARG to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# The THREADS_HAVE_PTHREAD_ARG variable holds the build result for this TRY_RUN().
# 
# Source file   : /usr/share/cmake-3.6.2/Modules/CheckForPthreads.c
# Executable    : /home/clegg/devel/tetris/build/CMakeFiles/cmTC_77300-THREADS_PTHREAD_ARG.exe
# Run arguments : 
#    Called from: [3]	/usr/share/cmake-3.6.2/Modules/FindThreads.cmake
#                 [2]	/usr/share/cmake-3.6.2/Modules/FindThreads.cmake
#                 [1]	/home/clegg/devel/tetris/tests/CMakeLists.txt

set( THREADS_PTHREAD_ARG 
     "PLEASE_FILL_OUT-FAILED_TO_RUN"
     CACHE STRING "Result from TRY_RUN" FORCE)

